-- 0018: SKU generator improvements (applied live 2026-07-07).
-- - skus.archived: hide generated SKUs from the default dashboard view.
-- - sku_conventions.product_template (jsonb): per-supplier "blue header" product
--   upload template (44 platform columns) seeded from SKU Convention Updated.xlsx.
--   The SKU dashboard exports generated SKUs in this format (CSV/Excel), with the
--   generated SKU filled into the `sku` column.

alter table public.skus add column if not exists archived boolean not null default false;
alter table public.sku_conventions add column if not exists product_template jsonb;

-- Seed product_template per supplier (values from the "blue" columns of the workbook).
update public.sku_conventions c set product_template = v.tpl::jsonb
from (values
('Liquidity Services Amazon BFL2','{"supplier": "Liquidity Services Inc", "name": "Waiting for Manifest", "cloud": "1", "psku": "LOAD-AMZCL", "packing": "Load", "fob_state": "CA-Los Angeles", "manifest_status": "Manifested", "peachtree_code": "LOAD-LAMZ", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "program": "LOAD-AMZCL", "store": "AMZ", "fob_zip": "90262", "make_an_offer": "1", "product_group": "Load Center"}'),
('Liquidity Services Amazon TUS','{"supplier": "Liquidity Services Inc", "name": "Waiting for Manifest", "cloud": "1", "psku": "LOAD-AMZCL", "packing": "Load", "fob_state": "CA-Los Angeles", "manifest_status": "Manifested", "peachtree_code": "LOAD-LAMZ", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "program": "LOAD-AMZCL", "store": "AMZ", "fob_zip": "90262", "make_an_offer": "1", "product_group": "Load Center"}'),
('Bstock Amazon BFL1','{"supplier": "Bstock-Amazon", "name": "Waiting for Manifest", "cloud": "1", "psku": "LOAD-AMZCL", "packing": "Load", "fob_state": "CA-Los Angeles", "manifest_status": "Manifested", "peachtree_code": "LOAD-BAMZ", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "program": "LOAD-AMZCL", "store": "AMZ", "fob_zip": "90262", "make_an_offer": "1", "product_group": "Load Center"}'),
('WayFair Perris Salvage','{"supplier": "Wayfair", "name": "WYF Salvage Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Unmanifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('WayFair Perris LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Smaller Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Perris Aged','{"supplier": "Wayfair", "name": "WYF Excess & Aged Inventory", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "New Overstock", "store": "WYF", "price_highlight": "14", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Perris QC','{"supplier": "Wayfair", "name": "WYF QC Imperfection Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WYF", "price_highlight": "16.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Aberdeen LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Large and Smaller Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "MD", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Aberdeen Salvage','{"supplier": "Wayfair", "name": "WYF Salvage Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "MD", "manifest_status": "Unmanifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('WayFair Jacksonville LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Large and Smaller Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "FL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Jacksonville Salvage','{"supplier": "Wayfair", "name": "WYF Salvage Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "FL", "manifest_status": "Unmanifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('Wayfair Lancaster,TX LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Large and Smaller Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Lancaster,TX Salvage','{"supplier": "Wayfair", "name": "WYF Salvage Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "TX", "manifest_status": "Unmanifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('Wayfair Lathrop,CA','{"supplier": "Wayfair", "name": "WYF Excess & Aged Inventory", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "New Overstock", "store": "WYF", "price_highlight": "14", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Romeoville,IL LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Large and Smaller Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "IL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Romeoville,IL Salvage','{"supplier": "Wayfair", "name": "WYF Salvage Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "IL", "manifest_status": "Unmanifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('Wayfair City of Industry,CA HDO','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Larger Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "11.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Portland,OR HDO','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Larger Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "OR", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "product_group": "Load Center"}'),
('WayFair Aberdeen AGED','{"supplier": "Wayfair", "name": "WYF Excess & Aged Inventory", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "MD", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "New Overstock", "store": "WYF", "price_highlight": "14", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Erlanger,KY AGED','{"supplier": "Wayfair", "name": "WYF Excess & Aged Inventory", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "KY", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "New Overstock", "store": "WYF", "price_highlight": "14", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Lancaster,TX Aged','{"supplier": "Wayfair", "name": "WYF Excess & Aged Inventory", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "New Overstock", "store": "WYF", "price_highlight": "14", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Kent,WA LQ','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Larger Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "WA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "12.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Perigold Houston,TX','{"supplier": "Wayfair", "name": "WYF Liquidation Returns - Larger Items", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Customer Returns", "store": "WYF", "price_highlight": "12.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('WayFair Jacksonville QC','{"supplier": "Wayfair", "name": "WYF QC Imperfection Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "FL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WYF", "price_highlight": "16.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Wayfair Romeoville,IL QC','{"supplier": "Wayfair", "name": "WYF QC Imperfection Loads", "cloud": "1", "psku": "LOAD-WYF", "packing": "Load", "category_1": "106", "fob_state": "IL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WYF", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WYF", "price_highlight": "16.5", "price_highlight_id": "% of Retail", "product_group": "Load Center"}'),
('Walmart Exit Store# 2217','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7767','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 3006','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 3865','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 3559','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "IL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6833','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 9202','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "KS", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 8103','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7049','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 4034','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "KS", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 9204','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "NV", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 3108','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "AZ", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6749','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "UT", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 4027','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMCMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6029','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "UT", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6009','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "IA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6012','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "TX", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6019','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CO", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6021','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6025','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "WI", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6026','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6031','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "AZ", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6037','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "OR", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6561','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7026','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "UT", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7033','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7039','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "WI", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 6060','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7089','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "CA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7092','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "WA", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7853','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "FL", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}'),
('Walmart Exit Store# 7552','{"supplier": "Walmart.com", "name": "Pending", "cloud": "1", "psku": "LOAD-WMCMDE", "packing": "Load", "category_1": "102", "fob_state": "IN", "manifest_status": "Manifested", "peachtree_code": "LOAD-WMDEB", "peachtree_qty": "1", "product_condition": "Shelf Pulls", "store": "WM", "price_highlight_id": "% of Retail", "product_group": "Load Center", "restrict_price_change": "1"}')
) as v(supplier, tpl)
where c.supplier = v.supplier;